<#ftl encoding='UTF-8'>

<main>
<h3>Wybierz swoje auto : </h3>
<div class="container-fluid">
    <form>
        <input type="text" placeholder="Wybierz markę pojazdu..." name="CarName">
        <input type="text" placeholder="Wybierz mode pojazdu..." name="CarModel">
        <input type="text" placeholder="Wybierz rok pojazdu..." name="CarYear">
        <input type="text" placeholder="Wybierz wersję pojazdu..." name="CarVersion">
    </form>
</div>

</main>

